name: Deploy FTPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: guinesoftware.com.br
          username: guinesoftware
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /www/painel/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github*
            **/.env*
            **/vendor*
            **/node_modules*
            **/.vscode*
            **/.idea*
